#pragma once

#define MAIN_BUTTON_WIDTH		500
#define MAIN_BUTTON_HEIGHT		100
#define MAIN_BUTTON_MARGIN		75
#define MAIN_BUTTON_INITIAL_Y	250
#define MAIN_BUTTON_INITIAL_X	158

#define TOTAL_BRICK_TYPES		5
#define BRICK_RESISTANCE1_INDEX 0
#define BRICK_RESISTANCE2_INDEX	1
#define BRICK_RESISTANCE3_INDEX	2
#define BRICK_RESISTANCE4_INDEX	3
#define BRICK_BONUS_INDEX		4

#define BRICK_RESISTANCE1_PATH	TEXT("./Assets/BrickResistance1.BMP")
#define BRICK_RESISTANCE2_PATH	TEXT("./Assets/BrickResistance2.BMP")
#define BRICK_RESISTANCE3_PATH	TEXT("./Assets/BrickResistance3.BMP")
#define BRICK_RESISTANCE4_PATH	TEXT("./Assets/BrickResistance4.BMP")
#define BRICK_BONUS_PATH		TEXT("./Assets/BrickBonus.BMP")