#pragma once
//Game constants 
#define MAX_PLAYERS 20
#define MAX_TOP_PLAYERS 10
#define MAX_BRICKS_IN_LINE 14
#define MAX_BRICK_LINES 7
#define MAX_BRICKS (MAX_BRICKS_IN_LINE * MAX_BRICK_LINES)
#define BRICKS_MARGIN 2
#define BRICKS_MAX_RESISTANCE 4
#define MAX_BONUS 15
#define MAX_BALLS 3

//Game dimensions
#define DIM_X_FRAME 800
#define DIM_Y_FRAME 600

#define GAME_BORDER_TOP 122
#define GAME_BORDER_LEFT 50
#define GAME_BORDER_RIGHT 746
#define GAME_BOARD_WIDTH (GAME_BORDER_RIGHT - GAME_BORDER_LEFT)
#define GAME_BOARD_HEIGHT (DIM_Y_FRAME - GAME_BORDER_TOP)

#define GAME_LIVES_START_X 75
#define GAME_LIVES_START_Y 71
#define GAME_LIVES_WIDTH 33
#define GAME_LIVES_MARGIN 10

#define GAME_SCORE_LEFT 575
#define GAME_SCORE_TOP 62
#define GAME_SCORE_RIGHT (GAME_SCORE_LEFT + 185) 
#define GAME_SCORE_BOTTOM (GAME_SCORE_TOP + 40)
#define GAME_SCORE_FONT_SIZE 46

#define GAME_BALL_WIDTH 25
#define GAME_BALL_HEIGHT 25

#define GAME_BALL_RANDOM_AREA_Y 200

#define GAME_BARRIER_Y 560
#define GAME_BARRIER_HEIGHT 35

#define BRICKS_WIDTH 48
#define BRICKS_HEIGHT 24
#define GAME_BRICKS_BOTTOM (BRICKS_HEIGHT * MAX_BRICK_LINES + GAME_BORDER_TOP)

#define GAME_BONUS_WIDTH 72
#define GAME_BONUS_HEIGHT 24

//Bonus types
//TODO: Change to match the number of implemented bonus
#define TOTAL_BONUS 4
#define BONUS_SPEED_UP 0
#define BONUS_SLOW_DOWN 1
#define BONUS_EXTRA_LIFE 2
#define BONUS_TRIPLE_BALL 3
#define BONUS_BIGGER_BARRIER 4
#define BONUS_SMALLER_BARRIER 5

//Game Status
#define IN_LOBBY 0
#define IN_GAME 1
#define GAME_OVER 2