#pragma once

//Name Constant
#define TAM 64
//Max Content Constant
#define MAX 256
//TOP10 Buffer
#define TOP10_SIZE (MAX * 10)

#define BUFFER_SIZE 50

//Shared Memory Name
#define BUFFER_MEMORY_CLIENT_REQUESTS TEXT("ARKANOID_BUFFER_MEMORY_CLIENT_REQUESTS")
#define BUFFER_MEMORY_SERVER_RESPONSES TEXT("ARKANOID_BUFFER_MEMORY_SERVER_RESPONSES")

//Mutex Name
#define MUTEX_CLIENT_REQUEST TEXT("ARKANOID_MUTEX_CLIENT_REQUEST")
#define MUTEX_SERVER_RESPONSES TEXT("ARKANOID_MUTEX_SERVER_RESPONSES")

//Semaphore Name
#define SEMAPHORE_CLIENT_REQUEST_ITEMS TEXT("ARKANOID_SEMAPHORE_CLIENT_REQUEST_ITEMS")
#define SEMAPHORE_CLIENT_REQUEST_EMPTY TEXT("ARKANOID_SEMAPHORE_CLIENT_REQUEST_EMPTY")

#define SEMAPHORE_SERVER_RESPONSE_ITEMS TEXT("ARKANOID_SEMAPHORE_SERVER_RESPONSE_ITEMS")
#define SEMAPHORE_SERVER_RESPONSE_EMPTY TEXT("ARKANOID_SEMAPHORE_SERVER_RESPONSE_EMPTY")

//Event Name
#define EVENT_CLIENT_MESSAGE_CHECK TEXT("ARKANOID_EVENT_CLIENT_MESSAGE_CHECK")

//Registry
#define REGISTRY_TOP10_PATH TEXT("Software\\ArkanoidGame")
#define TOP10_REGISTRY_VALUE TEXT("TOP10")
#define TOP10_PLAYER_COUNT TEXT("TOP10PlayerCount")

#define TOP10_DUMMY_VALUE TEXT("SO2;9999;XPTO;8000;Arkanoid;6666;")