#pragma once

//Name Constant
#define TAM 64
//Max Content Constant
#define MAX 256

#define BUFFER_SIZE 50

//Shared Memory Name
#define BUFFER_MEMORY_CLIENT_REQUESTS TEXT("ARKANOID_BUFFER_MEMORY_CLIENT_REQUESTS")
#define BUFFER_MEMORY_SERVER_RESPONSES TEXT("ARKANOID_BUFFER_MEMORY_SERVER_RESPONSES")

//Mutex Name
#define MUTEX_CLIENT_REQUEST TEXT("ARKANOID_MUTEX_CLIENT_REQUEST")
#define MUTEX_SERVER_RESPONSES TEXT("ARKANOID_MUTEX_SERVER_RESPONSES")

//Semaphore Name
#define SEMAPHORE_CLIENT_REQUEST_ITEMS TEXT("ARKANOID_SEMAPHORE_CLIENT_REQUEST_ITEMS")
#define SEMAPHORE_CLIENT_REQUEST_EMPTY TEXT("ARKANOID_SEMAPHORE_CLIENT_REQUEST_EMPTY")

#define SEMAPHORE_SERVER_RESPONSE_ITEMS TEXT("ARKANOID_SEMAPHORE_SERVER_RESPONSE_ITEMS")
#define SEMAPHORE_SERVER_RESPONSE_EMPTY TEXT("ARKANOID_SEMAPHORE_SERVER_RESPONSE_EMPTY")

//Event Name
#define EVENT_CLIENT_MESSAGE_CHECK TEXT("ARKANOID_EVENT_CLIENT_MESSAGE_CHECK")